import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ReduxProvider from './redux/ReduxProvider'
import DNDProvider from './drag-n-drop/components/DNDProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'TypeScript Playground',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
            <body className={inter.className + " dark"}>
                <ReduxProvider>
                    <DNDProvider>
                        {children}
                    </DNDProvider>
                </ReduxProvider>
            </body>
        </html>
    )
}
